listening-port=3478
# روی IP عمومی گوش بده تا از هر کلاینتی (هر IP) قابل‌اتصال باشد
listening-ip=91.107.160.235
relay-ip=91.107.160.235
external-ip=91.107.160.235
fingerprint
lt-cred-mech
user=coinepro:73f444932f1bc87233819d522592ac77
realm=fx.trade-future.ir
min-port=49160
max-port=49200
# اجازهٔ relay به هر مقصدِ peer (بدون محدودیتِ IP)
verbose
no-cli
no-tlsv1
no-tlsv1_1
