[program:ffmpeg-capture]
command=/capture.sh
environment=MEDIAMTX_HOST="mediamtx",PUBLISH_USER="%(ENV_PUBLISH_USER)s",PUBLISH_PASS="%(ENV_PUBLISH_PASS)s",CAP_DISPLAY=":20",DISPLAY_W="1024",DISPLAY_H="768",CAPTURE_FPS="15"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/tmp/ffmpeg.log
redirect_stderr=true
priority=40
