version = 5.6.0
archive_dir = /etc/letsencrypt/archive/fx.trade-future.ir
cert = /etc/letsencrypt/live/fx.trade-future.ir/cert.pem
privkey = /etc/letsencrypt/live/fx.trade-future.ir/privkey.pem
chain = /etc/letsencrypt/live/fx.trade-future.ir/chain.pem
fullchain = /etc/letsencrypt/live/fx.trade-future.ir/fullchain.pem
[renewalparams]
account = 2b5789639de24842aeedda4775a649e3
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
fx.trade-future.ir = /var/www/certbot
panel.fx.trade-future.ir = /var/www/certbot
user.fx.trade-future.ir = /var/www/certbot
academy.fx.trade-future.ir = /var/www/certbot
ig.trade-future.ir = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-06-22T16:22:06
