version = 5.6.0
archive_dir = /etc/letsencrypt/archive/mt5.fx.trade-future.ir
cert = /etc/letsencrypt/live/mt5.fx.trade-future.ir/cert.pem
privkey = /etc/letsencrypt/live/mt5.fx.trade-future.ir/privkey.pem
chain = /etc/letsencrypt/live/mt5.fx.trade-future.ir/chain.pem
fullchain = /etc/letsencrypt/live/mt5.fx.trade-future.ir/fullchain.pem
[renewalparams]
account = 2b5789639de24842aeedda4775a649e3
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
mt5.fx.trade-future.ir = /var/www/certbot
turn.fx.trade-future.ir = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-06-22T14:28:19
